repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: system
        types_or: [ python, pyi, jupyter ]
        args: [ ]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: system
        types_or: [ python, pyi, jupyter ]
        args: [ ]
        require_serial: true
      - id: nbstripout
        name: nbstripout
        description: 'nbstripout: strip output from Jupyter and IPython notebooks'
        entry: nbstripout
        language: system
        types: [ jupyter ]
        require_serial: true

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: '0.12.19' 
    hooks:
      - id: uv-export
        args: [ "--group", "doc", "--no-hashes", "-o", "docs/requirements.txt", "--format", "requirements-txt" ]
        files: '^uv\.lock$'
        verbose: true