[project]
name = "FAST-OAD"
description = "FAST-OAD is a framework for performing rapid Overall Aircraft Design"
readme = "README.md"
version = "__FAST_OAD_VERSION__" # This value is replaced by our CI routine during the build process.
license = { text = "GPL-3.0-only" }
keywords = [
    "aircraft",
    "design",
    "multi-disciplinary"
]
authors = [
    {name = "Christophe DAVID", email = "christophe.david@onera.fr"},
    {name = "Scott DELBECQ", email = "Scott.DELBECQ@isae-supaero.fr"}
]
maintainers = [
    {name = "Florent LUTZ", email = "Florent.LUTZ2@isae-supaero.fr"},
    {name = "Eric NGUYEN VAN", email = "Eric.Nguyen_Van@onera.fr"},
    {name = "Enrico STRAGIOTTI", email = "enrico.stragiotti@onera.fr"},
]
requires-python = ">=3.10,<3.15"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Physics",
]

dependencies = [
    # Version constraint is dynamically replaced by CI before publishing (see build_release.yml).
    # It should always match the FAST-OAD umbrella version to ensure consistency.
    "fast-oad-core>=__FAST_OAD_VERSION__",
    "fast-oad-cs25>=0.8.1"
]

[project.urls]
homepage = "https://github.com/fast-aircraft-design/FAST-OAD"
documentation = "https://fast-oad.readthedocs.io/en/stable/"

[tool.hatch.version]
source = "vcs"
fallback-version = "__FAST_OAD_VERSION__"  # used when no vcs/tag history is available (e.g. shallow clone, sdist rebuild)

[tool.hatch.build.targets.wheel]
packages = ["_fastoad"]

[tool.uv]
package = false

# Packaging system =============================================================
[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"