# -*- coding: utf-8 -*-
"""
  disc2_base.py generated by WhatsOpt. 
"""
# DO NOT EDIT unless you know what you are doing
# analysis_id: 102

from openmdao.api import ExplicitComponent


class Disc2Base(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Disc2 discipline """

    def setup(self):
        self.add_input('z', val=[5, 2], desc='')
        self.add_input('y1', val=1.0, desc='')

        self.add_output('y2', val=1.0, desc='')
        self.declare_partials('*', '*')
