# -*- coding: utf-8 -*-
"""
  functions.py generated by WhatsOpt. 
"""
#      This file is part of FAST : A framework for rapid Overall Aircraft Design
#      Copyright (C) 2019  ONERA/ISAE
#      FAST is free software: you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation, either version 3 of the License, or
#      (at your option) any later version.
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#      You should have received a copy of the GNU General Public License
#      along with this program.  If not, see <https://www.gnu.org/licenses/>.
from math import exp

from .functions_base import FunctionsBase


class Functions(FunctionsBase):
    """ An OpenMDAO component to encapsulate Functions discipline """

    def compute(self, inputs, outputs):
        """ Functions computation """

        z1 = inputs['z'][0]
        z2 = inputs['z'][1]
        x1 = inputs['x']
        y1 = inputs['y1']
        y2 = inputs['y2']

        outputs['f'] = x1 ** 2 + z2 + y1 + exp(-y2)
        outputs['g1'] = 3.16 - y1
        outputs['g2'] = y2 - 24.0
# Reminder: inputs of compute()
#   
#       inputs['x'] -> shape: 1, type: Float    
#       inputs['z'] -> shape: 1, type: Float    
#       inputs['y1'] -> shape: 1, type: Float    
#       inputs['y2'] -> shape: 1, type: Float      

# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(Functions, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Functions """
#   
#       	partials['f', 'x'] = np.zeros((1, 1))
#       	partials['f', 'z'] = np.zeros((1, 1))
#       	partials['f', 'y1'] = np.zeros((1, 1))
#       	partials['f', 'y2'] = np.zeros((1, 1))
#       	partials['g1', 'x'] = np.zeros((1, 1))
#       	partials['g1', 'z'] = np.zeros((1, 1))
#       	partials['g1', 'y1'] = np.zeros((1, 1))
#       	partials['g1', 'y2'] = np.zeros((1, 1))
#       	partials['g2', 'x'] = np.zeros((1, 1))
#       	partials['g2', 'z'] = np.zeros((1, 1))
#       	partials['g2', 'y1'] = np.zeros((1, 1))
#       	partials['g2', 'y2'] = np.zeros((1, 1))
