name: Build Binder image
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master

jobs:
  build-binder:
    runs-on: ubuntu-latest
    steps:
      - name: cache binder build on mybinder.org
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }}
